filacli = ()
listclientes = ()
treeclientes = ()
menserror = ()
listado = ()
listado2 = ()
listado3 = ()
ventcalendar = None
venacercade = None
venfiledialog = None
venfiledialog2 = None
venPrecio = None
calendar = None
filahabi = ()
listhabitaciones = []
treehabitaciones = ()
listcmbhab = []
cmbhab = ()
filares=()
listres = []
treeres = ()
panel = None
semaforo = None
numhabr = None
labels_factura = ()
ent_precios = ()
listservi = []
listfact = []
filaser = ()
treeser = ()
subtotal= None
ivafactura=None
totalfactura=None